### ISSUE TITLE
Error in read.loci "Locus file does not have required headers"

### ISSUE THREAD

**Issue by Iago-Junger** [josefin-werme/LAVA#12]
Hello, everybody, I hope you're well!

This week I was trying to run read.loci function. So, I read the genome partitioning tutorial on Github and followed the steps described. However, when I use the "LAVA_s2500_m25_f1_w200.blocks" file or another file that I create by using "./ldblock", LAVA returns me the following error 
"Error in read.loci("GenomePartioning/LAVA_s2500_m25_f1_w200.blocks") : 
  Locus file does not contain required headers"
Therefore, I need some help to know what I'm doing wrong

Thank you for the attention, all the best

Iago J.

![image](https://user-images.githubusercontent.com/85440627/134348775-950017b2-ebdd-4e88-b6f7-c45d26a7a4a1.png)
![image](https://user-images.githubusercontent.com/85440627/134349390-6bde6587-d6a9-403e-9e93-fa7eddf332e6.png)
![image](https://user-images.githubusercontent.com/85440627/134349454-f4c25576-8b49-4059-8762-71a18013558d.png)

**Comment by josefin-werme** [comment]
Hi, 

It is due to the format of the locus file.

The program assumes it will have capitalised headers and be white space space separated. 

You can inspect the file provided on the GitHub for an example (https://github.com/josefin-werme/LAVA/blob/main/support_data/blocks_s2500_m25_f1_w200.GRCh37_hg19.locfile <https://github.com/josefin-werme/LAVA/blob/main/support_data/blocks_s2500_m25_f1_w200.GRCh37_hg19.locfile>) 

Best, 

Josefin

**Comment by iagojunger1112** [comment]
Hello, 

now it worked! thank you :) 

All the best 

Iago J.
