### ISSUE TITLE
Error in eigen(cor(X)) : infinite or missing value in 'x'

### ISSUE THREAD

**Issue by ofrei** [josefin-werme/LAVA#13]
I'm getting the following error while running LAVA
![image](https://user-images.githubusercontent.com/13171449/134395681-e4edf5f3-c4d6-4eae-be05-5775207421f0.png)

I'm running ``lava_script.R`` as described in tutorial (with magma's ``g1000_eur``  as reference and with``blocks_s2500_m25_f1_w200.GRCh37_hg19.locfile`` as locus file)

The error seem to happen for a particular locus. I'm OK with n/a result for that locus so I can investigate input summary stats, but get the results for other loci.

**Comment by josefin-werme** [comment]
Hi, 

Im quite sure this issue is because some SNPs in the locus have zero variance, which causes an issue when standardising X. The ‘dev’ branch has a solution implemented for this already (i.e. checking and removing non-variant SNPs), which I plan on merging it with main in the coming 1-2 weeks but I am not entirely finished with the checks yet.

Would you mind perhaps trying out the dev branch already and see if it works? Cause if not it would be good to know what else is causing this so I can fix it.

Cheers,

Josefin

**Comment by ofrei** [comment]
Hi Josefin,
Thanks! I've triggered new runs from the dev branch.
For nwo I've kept the following in my LAVA_script.R:
```
        locus = try(process.locus(loci[i,], input), silent=T)                           # process locus
        if (class(locus)=="try-error") { next }
```
but I can see how often it crashes.
Also, I'm still getting these errors / warnings, which a probably "by design" (some loci might have that):
![image](https://user-images.githubusercontent.com/13171449/134679989-8fbade61-d467-4b84-845c-f89686644eba.png)
I'll count if there are less warnings like this in ``dev`` branch vs ``main``.

**Comment by josefin-werme** [comment]
Hi, 

Sorry I just discovered now that I never responded to this follow-up question!!

But yes you're right its by design. This just happens with extremely low or non-existent h2, in which the locus cannot be analysed anyway. 

It doesn't always happen for all phenotypes though, in which case it'll instead specify which ones weren't possible to process and you'll also notice those phenotypes are not present in the locus object. 

Best, 

Josefin
