### ISSUE TITLE
Vast majority of loci have fewer than 2 SNPs

### ISSUE THREAD

**Issue by lucasmavro** [josefin-werme/LAVA#20]
Hello,

I am trying to run LAVA and am running into an issue where the vast majority of loci aren't being analyzed because they have fewer than 2 SNPs. I have tried using non-munged sum-stats, which should increase the number of available SNPs. I am also only analyzing 2 phenotypes, so there should be a good amount of overlapping SNPs. The program states that 95480 SNPs are available prior to the analysis, which should mean approximately 40 SNPs/locus (95480 SNPs / ~2500 loci). Of course, the SNPs may not be evenly distributed across loci, but I still would think that the majority of loci should have more than 2 SNPs available.

Any idea what could be causing this issue?

Thanks for any insight you can provide.

Lucas

**Comment by josefin-werme** [comment]
Hi Lucas,

I would say that if the majority of loci have no SNPs, this is most likely due to the fact that these SNPs are not evenly distributed and that they are indeed clustering in a smaller number of loci. Generally, 90k SNPs for the whole genome is a very low number for these kinds of analyses (typical numbers are probably somewhere between 5-10M), so I would recommend using a data set with better coverage. 

All the best,

Josefin
