### ISSUE TITLE
Warning: Estimates too far out of bounds for phenotype(s)

### ISSUE THREAD

**Issue by IsabelaVelloso** [josefin-werme/LAVA#24]
Hello again!

I ran into another problem while trying to run the partial correlation analysis. While doing a bidirectional test, a warning appeared that my phenotypes are off the threshold for the 'param.lim' argument. I did not understand what this means and how to solve it, can someone help?
![Sem título](https://user-images.githubusercontent.com/81487259/167656828-0366aa0b-b24f-4e87-baec-99497dde8419.png)

Kind regards,
Isabela.

**Comment by cadeleeuw** [comment]
Hi,

Because of the nature of the model, it is possible for (partial) correlation estimates to be out of bounds, ie. smaller than -1 or greater than 1. To an extent this can just be due to noise, so as long as they are not too far out of bounds it is reasonable to assume that it's just that: there is genuine (partial) correlation close to 1 (or -1), and it's just the noise that's pushing the estimate a bit past that. 

However, instabilities in the genetic variance estimates can also cause correlation estimates to go out of bounds, and especially if those estimates are very far out of bounds it is likely to be because of such unstable variance estimates. In that case the correlation estimate wouldn't be reliable anymore, eg. the true genetic correlation might be close to zero but the estimate might be pushed well past 1 due to a very unstable genetic variance estimate (often these won't be significant anyway, but in some cases they might be). 

The param.lim parameter controls what is considered "not too far out of bounds", which by default here is set to 1.25; that is, correlation estimates between -1.25 and 1.25 are considered to be sufficiently reliable, anything beyond that are not. If you want to know what the estimate is for this locus, you can set that to a much higher value (eg. param.lim=10); however, because there is a good chance that the estimate is no longer reliable, you'd have to be careful in interpreting it even if it's significant. 

As a sidenote, very likely the reason that this is happening for this locus is because as you can see in the output the correlation between IGF1 and ADHDdemontis is pretty much 1. With the partial correlation, you are looking at the correlation between the remaining parts of the genetic components (the residuals) of pheno1 and pheno2 that aren't explained by the conditioned on variable(s) z, but here in the case of IGF1 almost nothing actually remains of its local genetic component after you condition on ADHDdemontis. So that residual of IGF1 will have a very small variance, and could well just be noise.

Best,
Christiaan de Leeuw

**Comment by IsabelaVelloso** [comment]
Dear Christiaan,

Thanks for the prompt response, it helped a lot in understanding my data. Sorry for the delay in responding, but you really gave me a direction for my studies. Thank you again!

Kind regards,
Isabela.

**Comment by NicolasC0** [comment]
Hello everyone!

I have a similar question. I'm trying to analyse the partial correlation between ADHD and paracetamol (PCTL)  conditioned for depression (MDD) but the value is out of bounds. However, if I try to set the paramater higher to see the value, it just appears as 1 despite it being a different number in the warning message and I'm somewhat confused by this. Am I doing something wrong?
![image](https://user-images.githubusercontent.com/89661540/192871878-e3db6c78-5792-4044-8638-c19d26ef3898.png)

**Comment by cadeleeuw** [comment]
Hi,

The difference is due to the fact that in the function output, correlations (and CI bounds) are truncated to +/-1. So the raw estimate in this case is the 1.281 reported in the warning.

Best,
Christiaan

**Comment by NicolasC0** [comment]
Hi!
Thank you for the quick response, I understand it now.

Best, 
Nicolas
