### ISSUE TITLE
Error in partial correlation analysis

### ISSUE THREAD

**Issue by IsabelaVelloso** [josefin-werme/LAVA#27]
Hello there!

I was running some partial correlationa analysis, and some of my loci got an error and I don't know why. Can someone help me understand and maybe solve this problem?
![Sem título](https://user-images.githubusercontent.com/81487259/175549012-1a5f1056-a726-46fb-ae30-780207a02dfb.png)

**Comment by josefin-werme** [comment]
Hi, 

This seems like a case where we have missed catching an error and printing an appropriate message.

If you are using publicly available data, is there any chance you would be able to share the data for one of the loci where this is happening so that we can track down exactly what is going on? (feel free to email me at j.werme@vu.nl)

Thank you in advance, 

Josefin

**Comment by cadeleeuw** [comment]
Hi,

I have added a fix to the code that should resolve this. It is currently only in the development branch (0.1.2), but will be propagated to the main branch with the next update. You can install the dev branch by adding the argument `ref="dev"` to the install_github() call, if you need this fix already (note that in this case the partial variances are simply negative, so the fix just catches the error; there still won't be any results for this partial correlation analysis either way).
