### ISSUE TITLE
Output headers

### ISSUE THREAD

**Issue by IsabelaVelloso** [josefin-werme/LAVA#28]
Hi there!
I have a question about the headers in the output results of the bivariate and partial correlation analysis of LAVA. I did not find in the git hub or in the paper a description of the data, and that would be very helpful since I am analysing all now. Therefore, can someone enlighten me about some of them? Like, what is the n.pcs in the bivariate analysis? And in the results of the partial correlation, why are there two r2? One for the first phenotype and other for the second? As I understand, the r2 is the determination coefficient between two phenotypes, so I don't know why is separeted. Also, the pcor in partial correlation is the value of partial correlation itself?
Thanks.

**Comment by josefin-werme** [comment]
Hi Isabella, 

In general, descriptions of all the output parameters can be found in the R function manuals, which you can access by entering ‘?[function]’ in R. So e.g ‘?run.bivar’ or ‘?run.pcor’. 

But to answer your specific questions, n.pcs are the number of pruned PCs used for the locus, and the reason there are two r2s in the partial correlation output is because they represent the r2 of the two target phenotypes with z (separately). And indeed, pcor is the estimate of the partial correlation. 

Best, 

Josefin
