### ISSUE TITLE
multiple loci at a time

### ISSUE THREAD

**Issue by frotsko** [josefin-werme/LAVA#29]
Hello all,
Hope you're all fine

I just wanted to ask if it is possible to obtain partial correlations across variants from different loci at the same time. That is, for instance, to obtain bivariate local rg across variants from a specific set of genes.

Thanks in advance!

Javier

**Comment by josefin-werme** [comment]
Hi, 

There is currently no option to analyse multiple loci jointly, but: you could always create custom loci that combines your genes of interest and analyse these. So instead of specifying the locus coordinates in your locus file (i.e. 'CHR', 'START', 'STOP'), you can provide a 'SNPS' column which just contains a semi colon separated string of all the SNPs within the genes you want to analyse. 

Best, 

Josefin
