### ISSUE TITLE
About warnings and errors in the analysis of tutorial data

### ISSUE THREAD

**Issue by ryo-kurosawa** [josefin-werme/LAVA#30]
Hello, I have a question about warnings and errors in  in the analysis of tutorial data.

When I performed univariate/bivariate tests in all the 37 partitions in tutorial data, I got the warnings like below in 7 tests in 222 tests (37 partitions x 6 traits = 222 tests).

> "Warning: Negative variances estimate for phenotype(s) 'asthma' in locus 230; Dropping these as they cannot be analyzed."

Also, When I performed multivariate/partial correlation tests in 10 partitions with more than 2 significant bivariate tests in tutorial data,  I got the errors like below in 2/10 partitions in multivariate tests and 3/10 partitions in partial correlation tests.

> [1] "~ Running multiple regression for outcome 'bmi', with predictors 'asthma', 'depression', 'diabetes', 'hypothyroidism', 'rheuma'"
> Error in run.multireg(locus, target = disease, phenos = diseases[diseases !=  :
>   Genetic covariance matrix of predictor phenotyopes is not invertible

> [1] "~ Running partial correlation for 'rheuma' and 'bmi', conditioned on 'depression' + 'hypothyroidism'"
> Warning: Estimates too far out of bounds (+-1.5) for phenotype(s) depression ~ rheuma (-1.965), hypothyroidism ~ rheuma (-1.996) in locus 950. Values will be set to NA. To change this threshold, modify the 'param.lim' argument

Furthermore, I got much more warnings and errors when I performed LAVA with my own data.

So, I have questions;
・Is it inevitable to get warnings or errors in LAVA?
・How can I interpret these warnings and errors?
・Can I ignore these warnings and errors and just use calculated data?

**Comment by josefin-werme** [comment]
Hi! 

These warnings are normal, and just a way of letting you know why a particular locus might not be possible or recommended to analyse (either due to risk of unstable estimates, or that there is simply not enough genetic variance to do so). 

Generally they can be ignored, but are useful to look at in case you wonder why a particular locus wasn't possible to analyse.

As for interpretation: 

The first warning that you included is generally due to a lack of genetic signal, and in cases where the variance estimates are negative you simply cannot proceed with any analyses for that particular phenotype. If there is a negative variance estimate for only a subset of phenotypes, this will be a warning as you can still analyse all the other phenotypes, but if it happens for all phenotypes in a locus it will be an error, and no locus object will be returned.

The second warning message is due to strong collinearity between the genetic components of the predictors, causing issues with inversion (which is required to be able to make the necessary calculations for the analysis). If you can identify the predictor phenotypes that are the most strongly correlated based on their bivariate rgs you might potentially be able to run the analysis it if you remove one or several of those phenotypes.

The third is simply due to the estimates being too far out of bounds, in which case pvalues etc will not be computed. If you want to do this anyway you can modify the param.lim argument, but keep in mind that the estimates are unstable. 

Let me know if you have any further questions! 

Best, 

Josefin

**Comment by ryo-kurosawa** [comment]
Now I understand the meanings of warnings and errors.  Thank you very much!
