### ISSUE TITLE
Retrieve genes from a locus by knowing the chromosome position 

### ISSUE THREAD

**Issue by zh-zhang1984** [josefin-werme/LAVA#36]
Dear authors,
When I run the LAVA pipleline, and identified some hotspots locus; however, I have difficulty in identifying the genes within the locus. Are there any recommended tools to retrieve gene ID or gene names by knowing the start and stop position in a chromosome. 
I have the information like:

```
> loci
    LOC CHR     START      STOP
1     1   1     10539   1376204
2     2   1   1376205   2215495
3     3   1   2215496   2983519
4     4   1   2983520   3582047
5     5   1   3582048   4281476
6     6   1   4281477   4773403
7     7   1   4773404   5362404
8     8   1   5362405   6136814
9     9   1   6136815   7711794
```

Thank you very much for your help.

**Comment by cadeleeuw** [comment]
Hi,

At the moment there isn't any built-in functionality in LAVA to do this. However, you could use something like the following R function for this:

```
gene.locations = read.table("genes.annot", header=T, stringsAsFactors=F) # columns: GENE, CHR, START, STOP

get.genes = function(genes, block.chr, block.start, block.stop) {
	out = genes[genes$CHR == block.chr & genes$START <= block.stop & genes$STOP >= block.start,]
	out$SIZE = out$STOP - out$START
	
	overlap.size = ifelse(out$STOP > block.stop, block.stop, out$STOP) - ifelse(out$START < block.start, block.start, out$START)
	out$PROP = overlap.size / out$SIZE

	return(out)
}
```

You'd just call this with the `gene.locations` data.frame as the first argument and the coordinates of the locus you want to extract the genes for as the other arguments. It returns a data.frame with all the overlapping genes, also adding columns with the total size of each gene, and the proportion of if that lies inside the given block.

You'd of course need a gene location file to put into this. Which is most useful will depend on your needs, but for example we have a file with gene locations for (protein coding) Entrez genes on the MAGMA site here: https://ctg.cncr.nl/software/magma. You can use gene locations from any other source as well though, as long as it has the required GENE, CHR, START, STOP headers. You do need to make sure the gene locations are for build GRCh37/hg19 though, since that's what the LAVA blocks use.
