### ISSUE TITLE
Hello dear all!

### ISSUE THREAD

**Issue by iagojunger** [josefin-werme/LAVA#4]

**Comment by iagojunger** [comment]
Hello dear all! 

I’m a beginner in coding as well as R language, so I’m struggling a little bit trying to use LAVA, and I’ll be very grateful if you can help me. In sum Rstudio can’t identify the function “input” that you use in “input = process.input”. So here below are my steps.
I started by installing the packages needed:

install.packages("BiocManager")
BiocManager::install("snpStats")
install.packages("devtools")
devtools::install("~/Programs/R/lava")

	After that, I use the “library” function to attach these packages so I could start inputting the data. 

library(lava)
library(BiocGenerics)
library(BiocManager)
library(BiocVersion)
library (devtools)
library(snpStats)

	Next, I tried to use “input” by inputting the data you disponibilized in /vignettes, here is what I wrote:

input = process.input(input.info.file="vignettes/data/input.info.txt",           
            sample.overlap.file="vignettes/data/sample.overlap.txt",
ref.prefix="vignettes/data/g1000_test",
phenos=c("depression","neuro","bmi"))  

However, Rstudio couldn’t identify “input” as a function, so I could not continue my analysis. That's it, I appreciate if you could solve this :)

**Comment by josefin-werme** [comment]
Hi,

What is the exact error message you get? Would you mind taking a screenshot so I can see the code as well? The function is called 'process.input' rather than 'input', so if R complains there is no function called 'input' it might be the code (though the code you showed me looks correct). 

Do you see the function description of you enter the command '?process.input' ?

You also don't need to load all those packages btw :) once you've installed them lava will just use them directly, so you only need to load lava.

Best,

Josefin

**Comment by iagojunger** [comment]
Hi! 
First of all, thank you so much for answering my message :)

Yes, I was referring to _“process.input”_ function . So, when I enter that the program doesn’t identify it as a function, I’ll send you some prints of errors.

This is the error messege 
_Error in process.input(input.info.file = "C:/Users/iagoj/Documents/LAB/Aplicação+do+LAVA/Test_sumstats/input.info.txt",  : 
  não foi possível encontrar a função "process.input"_     -> unable to find function "process.input"

I'm brazilian btw, so the translation is in sequence 

Also, thank you for telling me about the loading of packages :)

Best, 

Iago Junger


![image](https://user-images.githubusercontent.com/76215768/106471048-035dc300-6480-11eb-94ae-ca38d36c982d.png)

**Comment by josefin-werme** [comment]
Thank you for the screenshot! 

I cannot see anything wrong with the code, but another user did note that there was a conflict between the lava package name and another existing package, so I have therefore renamed my package to call it ‘LAVA’ in capital letters instead. So perhaps this issue could be due to the wrong package being loaded.

Could you try downloading the most recent version and see if it works? There should also be a message when you load LAVA (like ‘Running LAVA version …’), so if you dont get this message, that suggests the package is not properly loaded.

All the best,

Josefin

**Comment by iagojunger** [comment]
Yes, for shure! I'll download that, but where I can download this? is it in that paste call R?

Best,
Iago

**Comment by josefin-werme** [comment]
You can either download the newest package version manually from Github (https://github.com/josefin-werme/LAVA <https://github.com/josefin-werme/LAVA>), or just re-install the newest version using this command in R:
devtools::install_git("https://github.com/josefin-werme/LAVA.git")
But make sure to follow the most recent tutorial on the GitHub page as some functions have been updated! :)

Best, 

Josefin

**Comment by iagojunger** [comment]
Thank you so much for helping me!

I'll try to instal the newest version and keep you posted!

All the best, 
Iago

**Comment by josefin-werme** [comment]
Happy to help! :)
