### ISSUE TITLE
Zero p-values in run.univ at non GWAS significant loci.

### ISSUE THREAD

**Issue by gouthamatla** [josefin-werme/LAVA#47]
Hi ,

Thanks for developing this excellent tool. I am looking at the run.univ() output. I noticed that I get too many loci to be significant (p<2e-5). When I inspected, most of those loci (with p==0) do not have any genome-wide or marginally significant SNPs for that trait in that locus. May I ask why this happens ? I can work on loci that has at least one GWAS sígnicant SNP but would like to know why this happens.

**Comment by cadeleeuw** [comment]
Hi,

Strong (and more or less global) inflations of the univariate signal from the LAVA results, relative to the input GWAS, generally are indicative of either a) something going wrong with the alignment of the SNP effects with the reference data, or b) a significant mismatch between the summary statistics and the reference data in terms of ancestry/LD. 

My suggestion would be to start by verifying that the allele columns in the summary statistics provided to LAVA are correct, ie. that these consistently indicate the effect allele for that SNP (rather than eg. the minor allele). An input issue of this nature is usually the cause of this sort of problem.

Best,
Christiaan
