### ISSUE TITLE
Question about locus file

### ISSUE THREAD

**Issue by floryhyy** [josefin-werme/LAVA#6]
Hello!
  Thank you for developing this tool!
  I'm trying to run this analysis on two traits. And I have been following the readme successfully until the part that requires the locus object. I am not sure what should I provide as the locus input file. Do I only include significant locus or are there other criteria?

Best,
Flory

**Comment by josefin-werme** [comment]
Hi Flory,

Just to clarify, which function is it exactly that you struggle with? Is it the read.loci() function, the process.locus() function, or any of the following analysis functions that use the locus object, like run.univ() / run.bivar() etc?

The read.loci() function just needs the file name of the locus definition file and will read in this file. The process.locus() function then just takes a single row from that locus definition file (i.e. the coordinates for a single locus) and will create a locus object by processing the sumstats that are relevant for that locus. Once you have done so, you can just pass that locus object to any of the analysis functions to evaluate univariate significance or genetic correlations within the locus. The process.locus() function has no criteria other than checking that there are not too few shared SNPs or negative variances within the locus, but we do recommend that you use the univariate test (i.e. the run.univ() function) afterwards as a filtering step to exclude loci / phenotypes that do not show sufficient levels of genetic signal before proceeding with the genetic correlation analysis. But you can decide yourself what this threshold should be.

I hope this clarifies a bit, but if not, please let me know exactly which part / function you are stuck on and I'll try to help you further.

Cheers, 

Josefin

**Comment by floryhyy** [comment]
Hello Josefin,
  I'm asking about the read.loci(). Currently, I do not have a  locus definition file for my data, I just got a GWAS file (with SNP chr, bp, beta,pvalue etc...). So I tried to use the locus file in the github, support_data/blocks_s2500_m25_f1_w200.locfile, and that give me an error. So I was wondering should I create a locus definition file for my data, if so, how should I do it ?

**Comment by josefin-werme** [comment]
Thank you for clarifying! That file should work, what error are you getting? 

Did you also already try running through the tutorial using the example files in the ‘vignettes/data’ folder btw?

**Comment by floryhyy** [comment]
oh sorry, I misremembered my problem, the error actually occured on process.locus(), below is the message

 > locus = process.locus(loci[1,], input)
[1] "Error: Negative variance estimate for all phenotypes in locus 1"
> ls(locus)                               # inspect locus
Error in as.environment(pos) : using 'as.environment(NULL)' is defunct

and I have not tried the example files, I will try it now.

**Comment by josefin-werme** [comment]
No problem :)

This error occurs when the estimated genetic variance or residual in the locus is negative. This most likely occurs when there is no signal in the locus, and will result in the locus object being be set to a NULL variable (as it cannot be analysed anyway).

If you want to automate your analysis and iterating over several loci later, I would recommend to add the check:

	if (!is.null(locus)) { … }

before applying any analysis functions to your locus (see the example script at the very bottom of the tutorial). Otherwise your script might be terminated. 

Let me know if you have any further questions / issues!

All the best, 

Josefin

**Comment by floryhyy** [comment]
Hi Josefin,
  Thanks for all the help, I got all the problems sorted out and ran the package successfully!
  Though I still have a question about the locus file, how you define and come up with those 2495 loci? I have not been able to find the relative information in the paper yet. 
  
Best,
Flory

**Comment by josefin-werme** [comment]
Great to hear you got it working!

Details about our definition of loci can be found in the Methods section on page 29 under ‘Genome partitioning’. In short, we developed a program (see https://github.com/cadeleeuw/lava-partitioning) which uses the LD information between SNPs to segment the genome into approximately equal sized, semi-independent blocks. The exact number of loci we ended up with was a consequence of the specific parameter settings we used, in particularly the minimum number of SNPs per locus. In our case, we set this to 2500, which resulted in our loci being approximately 1Mb on average.

If you want to experiment with different locus sizes you can always run the program with different settings. You also don't need to define loci the way we did, you could also create you own locus file based on what ever criteria you like. You could e.g. use gene locations or clumped regions from a GWAS, if that is relevant to your research question (instead of coordinates, you can use ‘;’ separated SNP list as locus definitions if that is more convenient). Note though that while I have not done a formal evaluation of what the optimal locus size, I have noticed that if you make your loci too small it will start affecting your power at some point. But feel free to experiment!

Cheers,

Josefin

**Comment by ofrei** [comment]
@josefin-werme A quick question to confirm genomic build for  [blocks_s2500_m25_f1_w200.locfile](https://github.com/josefin-werme/LAVA/blob/main/support_data/blocks_s2500_m25_f1_w200.locfile) file - is it based on ``hg19`` genome build ? I assume so because [here] (https://github.com/cadeleeuw/lava-partitioning) it is described as follows:
```
The LD blocks generated and used for the primary LAVA paper are included here as well. 
These were generated using the 1,000 Genomes (EUR) data found here https://ctg.cncr.nl/software/magma  
at default values for the blocking algorithm except with the mininum block size set to 2500. 
No further post-hoc filtering was applied.
```
And [magma](https://ctg.cncr.nl/software/magma) says ``The SNP locations in the data are in reference to human genome Build 37``. So it must be ``hg19 / GRCh37``, correct?

**Comment by josefin-werme** [comment]
Hi @ofrei,

That is indeed correct! 

I will make sure this is stated on the tutorial page.

Best, 

Josefin

**Comment by ofrei** [comment]
@josefin-werme thanks!!

**Comment by zh-zhang1984** [comment]
> 

Hi Josefin
Thank you for your detailed reply to these questions and I really learned much. I have a question regarding the loci. May I apply the file "blocks_s2500_m25_f1_w200.GRCh37_hg19.locfile" for our own real data? or is that only an example? 
you mention "In our case, we set this to 2500, which resulted in our loci being approximately 1Mb on average."---did you mean we can have a number of 1Mb loci; but the  file"blocks_s2500_m25_f1_w200.GRCh37_hg19.locfile"  contains only 2495 loci.
