### ISSUE TITLE
Some questions regarding the LAVA method of GWAS input

### ISSUE THREAD

**Issue by nvice111** [josefin-werme/LAVA#64]
Dear Josefin Werme,  @josefin-werme 

email: [j.werme@vu.nl](mailto:j.werme@vu.nl)
Hello, I have some questions regarding the LAVA method:

1. For GWAS summary data, besides the filtering for 'info' and exome chip markers mentioned in your paper, is there any other preprocessing required, such as filtering for MAF, or should we input the complete GWAS data as it is?

"As this study relied on publicly available summary statistics (Table 1), sample sizes for the real data analyses were determined according to the maximum available. When per SNP imputation quality metrics were present, we filtered out any SNPs with an imputation quality ('info') score <0.9, and for the CAD summary statistics specifically, we excluded all exome chip markers due to the large sample size differences compared to the other SNPs."

2. Regarding the input of GWAS summary data, for the column N representing sample sizes, following your statement that "sample sizes for the real data analyses were determined according to the maximum available", if the sample size varies per SNP, should it be adjusted to the maximum available, or is it permissible for each SNP to have different sample sizes?

Thank you very much for your help. I have also posted the same question on GitHub (user nvice111, [1961606711@qq.com](mailto:1961606711@qq.com)), and if possible, you could reply directly on GitHub.

Lou Chen 

Wenzhou medical universty

[louchen2004@163.com](mailto:louchen2004@163.com)

**Comment by cadeleeuw** [comment]
Dear Lou Chen,

We generally recommend filtering the reference data on a MAF of at least 0.5% as in the LAVA paper, which would implicitly filter low MAF SNPs from the summary statistics as well, but beyond that (and the mentioned imputation quality filter) no additional filtering is needed. For the sample size, it is no problem if the sample size varies across SNPs, and indeed if such a sample size column is available in the data it is recommended that you use that rather than a uniform sample size for the cohort.

Best,
Christiaan de Leeuw

**Comment by nvice111** [comment]
Thank you for your answer, it helps me a lot！
