### ISSUE TITLE
Discordant results between LAVA and LDSC

### ISSUE THREAD

**Issue by actright7** [josefin-werme/LAVA#65]
Dear Dr Josefin and Colleagues, thank you for developing this powerful software. In our analysis, we found a positive genetic correlation between two traits (say A and B) using LDSC (rg: 0.22, P: 1.80E-09). These results were replicated using other GWAS data for both A and B. Also, we used another method which was consistent with LDSC's finding, in terms of effect direction between A and B.  On the other hand, we used LAVA and found the below results which are largely not consistent (more in the opposite direction) with LDSC. It may also be important to mention that our gene analysis found genes shared by A and B in the 2351 and 962 loci, while meta-analysis did not find these loci. Please, can you help provide insight into why LAVA was not consistent with LDSC in this instant? How can these types of results be explained?

locus | phen1 | phen2 | rho | p
2351 | A | B | -0.61 | 4.89E-33
962 | A | B | -0.37 | 4.18E-04
960 | A | B | -0.53 | 1.64E-03
464 | A | B | 0.88 | 3.92E-03
963 | A | B | 0.12 | 4.07E-03
954 | A | B | -0.74 | 1.50E-02

Thank you very much for your help and kind response.

**Comment by cadeleeuw** [comment]
Hi,

Global genetic correlations can be seen as essentially a (weighted) average across all the local genetic correlations, so an average of around 2500 local rG's with the standard LAVA partitioning. As such, it is quite possible that some of the local genetic correlations are negative, but for enough others to be positive for the sign of the global rG to be positive as well. 

This is presumbly the case in your analysis as well. An important consideration here is that because it is localized, power is much more of a factor for LAVA local genetic correlations than it is for LDSC global genetic correlations, since the smaller number of SNPs going into each p-value results in a much less favorable signal to noise ratio (while at the same time there are more p-values, and thus a higher multiple testing burden as well). Although in your present analyses you didn't find much in the way of significant positive local rG's, it is likely that many of those do exist but simply require more GWAS signal to be detected. 

Best,
Christiaan de Leeuw

**Comment by actright7** [comment]
Thanks very much for your response and insights. I appreciate it. Kind regards
