### ISSUE TITLE
Global rg and local rg

### ISSUE THREAD

**Issue by dqq0404** [josefin-werme/LAVA#79]
Hi,
Global rg between A and B from ldsc was -0.08 (insignificant,P=0.2). But this pair had 20 significant correlated regions, and in all of these regions, some SNPs of trait A had P < 5e-8, but all SNPs of trait B had P > 5e-8 or even larger. Is this reasonable?
Note that heritability of trait A was 0.058, B was 0.012. Does LAVA recommend heritability of a trait must > 0.05?

**Comment by cadeleeuw** [comment]
Hi,

This is in itself not unreasonable. This is something that may well happen if the genetic overlap between two traits is relatively narrow, ie. it is concentrated in only a small number of regions on the genome. In that case you would indeed expect to see little or no global genetic correlation, since most of the genetic variance of either trait is not shared with the other, but the local genetic correlations would still tend to show up. 

An extreme example of this is with molecular phenotypes, eg. gene expression (ie. eQTL data), where the genetic signal for the gene expression is usually concentrated almost entirely in and around that gene's transcription region, and so it's global genetic correlation with almost any non-molecular, polygenic phenotype will be essentially zero (because the other phenotype will have lots of genetic signal elsewhere on the genome), even if the local genetic correlation in that transcription region is very strong. And the same can certainly also happen between two polygenic phenotypes.

That there are no genome-wide significant SNPs in the regions for trait B is also not inherently a problem. LAVA aggregates signal across the region you're analyzing, so it can still work fine and have reasonable power as long as the LAVA univariate p-value is sufficiently low. Hence why we recommend using cut-offs on the univariate p-values, and don't specifically require global heritability to be above 0.05 (or any other threshold). 

Best,
Christiaan

**Comment by dqq0404** [comment]
Thanks for your patient answer!!
