### ISSUE TITLE
non-numeric argument to binary operator

### ISSUE THREAD

**Issue by giuseppe-fanelli** [josefin-werme/LAVA#9]
Dear Josefin,
Thanks a lot for your amazing work.
I was trying to run LAVA considering a number of traits.
I got the following error.. what could this be due to? Something about the sumstats (I didn't find anything wrong) or the fact that some sumstats are from binary traits (indicated with 1 and 0 in the input.info file as suggested in your tutorial) but have betas and not ORs?

Running LAVA version 0.0.6
[1] "...Reading in sumstats"
Error in input$sum.stats[[i]]$P/2 :
  non-numeric argument to binary operator
Calls: process.input -> process.sumstats -> qnorm
Execution halted

Many thanks
Giuseppe

**Comment by josefin-werme** [comment]
Dear Guiseppe,

The fact that you have betas is not a problem! Though it is for continuous phenotypes where you can just set the cases/controls to 1/0, binary phenotypes need the case/control samples to reflect the actual case control ratio.

What seems to be causing this error though is that the p-value column contains non-numeric entires. This could be due to e.g. unconventional ’NA’s (such as ‘.’) rather than there being anything wrong with your p-values.

Perhaps have a look to see if that is the case? And if so just replace them with standard NA’s and try again. I will make sure I add a proper check for this in case someone else runs into this problem in the future! 

Cheers,

Josefin

**Comment by polpett** [comment]
Dear Josefin,
thanks a lot for your answer.
I solved the previous error by prefiltering the Pvalues columns with 
`cat input.sumstats | \
awk 'NR==1 || ($5 > 0 && $5 < 1) {print}' > output.sumstats`
where $5 is the column of interest.

However, I encountered another error. Everything works using the toy data provided and using one locus at a time. But I'm trying to run the analyses on the entire set of loci provided in "support_data". I first split this file into 40 subfiles of equal length and adapted your Rscript to parallelize the job on multiple cores on one node in order to use HPC resources more efficiently.
The error is the following:

Running LAVA version 0.0.6
Error in rbind(deparse.level, ...) :
  numbers of columns of arguments do not match
Calls: write.table -> is.data.frame -> do.call -> <Anonymous> -> rbind
Execution halted

what could this be due to? 

Many thanks again!
Giuseppe

**Comment by josefin-werme** [comment]
Hi, 

It seems like there are different numbers of columns in the list that stored all the data, hence why the do.call(rbind,x) doesn’t work.

You can guard against this by adding a check before storing the bivariate results to ensure they are not NULL. If that does not solve it, however, would you mind sharing the analysis script with me? Either you can just send it here, or email me at ***@***.*** ***@***.***> (what ever you prefer).

Best,

Josefin
